### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by utkarshakandale** [jeremy-shannon/Intro-to-Machine-Learning-Udacity#1]
I encountered the following error while running the udacity-Intro-to-Machine-Learning/Decision tree/dt_author_id.py.

Traceback (most recent call last):
  File "dt_author_id.py", line 31, in <module>
    print clf.score(pred,labels_test)
  File "C:\Python27\lib\site-packages\sklearn\base.py", line 290, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Python27\lib\site-packages\sklearn\tree\tree.py", line 416, in predict
    X = self._validate_X_predict(X, check_input)
  File "C:\Python27\lib\site-packages\sklearn\tree\tree.py", line 377, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "C:\Python27\lib\site-packages\sklearn\utils\validation.py", line 552, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 1. ... 1. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Can you tell me how to solve this?

**Comment by ijeendu** [comment]
If you want to use the score function, then line your line 31 should read: 'print clf.score(features_test, labels_test)'. It is the accuracy_core metrics that takes (pred, labels_test) as parameters
